USE my_canvas;

LOAD DATA LOCAL INFILE "student.csv" INTO TABLE student FIELDS TERMINATED BY "," IGNORE 1 LINES;

LOAD DATA LOCAL INFILE "course.csv" INTO TABLE course FIELDS TERMINATED BY "," IGNORE 1 LINES;

LOAD DATA LOCAL INFILE "assignment.csv" INTO TABLE assignment FIELDS TERMINATED BY "," IGNORE 1 LINES;

LOAD DATA LOCAL INFILE "takes.csv" INTO TABLE takes FIELDS TERMINATED BY "," LINES TERMINATED BY '\r\n' IGNORE 1 LINES
  (studentID, cName, cNo, semester, year, @lttr) SET letter = NULLIF(@lttr,'');

LOAD DATA LOCAL INFILE "tas.csv" INTO TABLE tas FIELDS TERMINATED BY "," IGNORE 1 LINES;

LOAD DATA LOCAL INFILE "post.csv" INTO TABLE post FIELDS TERMINATED BY "," IGNORE 1 LINES;

LOAD DATA LOCAL INFILE "tag.csv" INTO TABLE tag FIELDS TERMINATED BY "," LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE "grades.csv" INTO TABLE grades FIELDS TERMINATED BY "," IGNORE 1 LINES
  (cName, cNo, semester, year, dueDate, studentID, @score, graderID) SET score = NULLIF(@score,'');
